In [21]:
import numpy as np
import pandas as pd
import random
import joblib
from pycaret.regression import *

In [2]:
df = pd.read_csv('./car/grandeur_firstName_dummies.csv')
df

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,14,121523,True,False,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,790
1,19,69368,False,True,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,2190
2,18,94692,False,True,False,False,False,False,False,False,...,0,1,1,0,1,0,0,0,1,1990
3,18,79252,False,True,False,False,False,False,False,True,...,0,1,0,0,0,0,0,0,0,1795
4,18,139269,False,True,False,False,False,False,False,False,...,0,1,1,0,0,0,1,0,1,1339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,10,97366,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,590
1973,11,170000,True,False,False,False,False,False,False,False,...,1,1,1,1,0,0,0,0,0,459
1974,19,120000,False,True,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,1690
1975,13,128220,True,False,False,False,False,False,False,True,...,0,1,1,0,0,0,0,0,0,979
1976,21,82312,False,False,False,False,False,False,True,False,...,0,0,0,0,0,0,0,0,0,3350

In [6]:
newCol = np.array(df.columns)

In [14]:
newDF = pd.DataFrame(columns=newCol[:-1])

In [15]:
newDF

Empty DataFrame
Columns: [year, distance, name_HG, name_IG, name_TG, name_normal, name_the_all_new, name_the_luxury, name_the_new, fuel_LPG, fuel_diesel, fuel_gasoline, fuel_hybrid, color_black, color_gray, color_others, color_silver, color_white, sunroof, HID, Al_wheel, auto_mirror, DLR, sunroof_pano, roof_rack, LED, HBA, ghost_door, sliding_door, side_step, adap_h, driver_heated_seat, driver_ventilated_seat, power_steering, steering_remote, leahter_seat, driver_elec_seat, pass_elec_seat, back_elec_seat, driver_memory_seat, massage_seat, supervision_cluster, paddle_shift, hi_pass, pass_memory_seat, back_heated_seat, amb_light, walkin_seat, sun_visor, pass_ventilated_seat, back_ventilated_seat, back_sensor, side_airbag, driver_airbag, pass_airbag, back_camera, around_view, blackbox, ABS, ECS, TCS, ESC, LDWS, bur_alarm, TPMS, knee_airbag, parking_sensor, front_carmera, AEB, smartkey, power_window, auto_doorlock, fullauto_aircon, auto_light, auto_parking, elec_parking_break, HUD, ECM, cruise_control, auto_trunk, heated_steering, keyless_doorlock, rain_sensor, stopNgo, wireless_charge, navi, CDrom, CD_changer, av_sys, mp3, AUX, USB, handsfree, iPod, back_monitor, mirroring, non_genu_navi, bluetooth]
Index: []

[0 rows x 98 columns]

In [16]:
sample = [0] * len(newDF.columns)
len(sample)

98

In [17]:
newDF.loc[0] = sample

In [18]:
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
model = load_model('./model/grandeur_auto')

Transformation Pipeline and Model Successfully Loaded

In [24]:
model

Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['year', 'distance', 'sunroof',
                                             'HID', 'Al_wheel', 'auto_mirror',
                                             'DLR', 'sunroof_pano', 'roof_rack',
                                             'LED', 'HBA', 'ghost_door',
                                             'sliding_door', 'side_step',
                                             'adap_h', 'driver_heated_seat',
                                             'driver_ventilated_seat',
                                             'power_steering',
                                             'steering_remote', 'leahter_seat',
                                             'driver...
                                                           max_cat_to_onehot=None,
                                                           max_delta_step=None,
                                                           max_depth=6,
                                                           max_leaves=None,
                                                           min_child_weight=4,
                                                           missing=nan,
                                                           monotone_constraints=None,
                                                           multi_strategy=None,
                                                           n_estimators=100,
                                                           n_jobs=-1,
                                                           num_parallel_tree=None,
                                                           random_state=4724, ...)),
                                             ('Random Forest Regressor',
                                              RandomForestRegressor(n_jobs=-1,
                                                                    random_state=4724)),
                                             ('Lasso Regression',
                                              Lasso(alpha=0.45,
                                                    random_state=4724))],
                                 n_jobs=-1))])

In [25]:
sample

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [29]:
prediction = predict_model(model, newDF)

[LightGBM] [Warning] feature_fraction is set=0.7, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

In [279]:
int(prediction['prediction_label'][0])

840

In [36]:
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
newDF['year'] = 20
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [101]:
from datetime import datetime

In [151]:
datetime.now().microsecond

439184

In [389]:
random.seed(int(datetime.now().microsecond))

In [391]:
sample_rand = [random.randint(0, 1) for _ in range(93)]
len(sample_rand)

93

In [396]:
rand = [random.randint(0, 1) for _ in range(77)]
print(rand)

[1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0]

In [392]:
newDF.loc[:, [i for i in list(newDF.columns) if i not in ['year', 'distance', 'name_HG', 'AUX', 'mp3']]] = sample_rand

In [398]:
options

['AUX', 'bluetooth', 'USB']

In [397]:
df_options.loc[:, [i for i in list(df_options.columns) if i not in options]] = rand

C:\Users\1104-27\AppData\Local\Temp\ipykernel_10540\1267960205.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_options.loc[:, [i for i in list(df_options.columns) if i not in options]] = rand

In [356]:
newDF.iloc[0].value_counts()

0
0    53
1    45
Name: count, dtype: int64

In [226]:
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,20,0,0,0,1,0,0,1,1,1,...,0,0,0,1,0,1,0,0,1,1

[0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0]

In [255]:
df_01 = pd.read_csv('./car/grandeur_firstName_dummies.csv')
df_02 = pd.read_csv('./car/k5_firstName_dummies.csv')
df_03 = pd.read_csv('./car/morning_firstName_dummies.csv')
df_04 = pd.read_csv('./car/tucson_firstName_dummies.csv')

In [256]:
columns_grandeur = np.array(df_01.columns)
columns_k5 = np.array(df_02.columns)
columns_morning = np.array(df_03.columns)
columns_tucson = np.array(df_04.columns)

In [450]:
columns_grandeur['']

array(['year', 'distance', 'name_HG', 'name_IG', 'name_TG', 'name_normal',
       'name_the_all_new', 'name_the_luxury', 'name_the_new', 'fuel_LPG',
       'fuel_diesel', 'fuel_gasoline', 'fuel_hybrid', 'color_black',
       'color_gray', 'color_others', 'color_silver', 'color_white',
       'sunroof', 'HID', 'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano',
       'roof_rack', 'LED', 'HBA', 'ghost_door', 'sliding_door',
       'side_step', 'adap_h', 'driver_heated_seat',
       'driver_ventilated_seat', 'power_steering', 'steering_remote',
       'leahter_seat', 'driver_elec_seat', 'pass_elec_seat',
       'back_elec_seat', 'driver_memory_seat', 'massage_seat',
       'supervision_cluster', 'paddle_shift', 'hi_pass',
       'pass_memory_seat', 'back_heated_seat', 'amb_light', 'walkin_seat',
       'sun_visor', 'pass_ventilated_seat', 'back_ventilated_seat',
       'back_sensor', 'side_airbag', 'driver_airbag', 'pass_airbag',
       'back_camera', 'around_view', 'blackbox', 'ABS', 'ECS', 'TCS',
       'ESC', 'LDWS', 'bur_alarm', 'TPMS', 'knee_airbag',
       'parking_sensor', 'front_carmera', 'AEB', 'smartkey',
       'power_window', 'auto_doorlock', 'fullauto_aircon', 'auto_light',
       'auto_parking', 'elec_parking_break', 'HUD', 'ECM',
       'cruise_control', 'auto_trunk', 'heated_steering',
       'keyless_doorlock', 'rain_sensor', 'stopNgo', 'wireless_charge',
       'navi', 'CDrom', 'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB',
       'handsfree', 'iPod', 'back_monitor', 'mirroring', 'non_genu_navi',
       'bluetooth', 'price'], dtype=object)

In [268]:
np.save('./model/columns_grandeur', columns_grandeur)
np.save('./model/columns_k5', columns_k5)
np.save('./model/columns_morning', columns_morning)
np.save('./model/columns_tucson', columns_tucson)

In [262]:
name = 'HG'

In [263]:
tmp = 'name_' + name

In [266]:
newDF[[tmp]] = 1
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,20,0,1,1,0,1,0,1,0,1,...,1,0,0,1,1,1,0,1,1,0

In [286]:
tmp1 = np.load('./model/columns_grandeur.npy', allow_pickle=True)
tmp2 = np.load('./model/columns_k5.npy', allow_pickle=True)
tmp3 = np.load('./model/columns_morning.npy', allow_pickle=True)
tmp4 = np.load('./model/columns_tucson.npy', allow_pickle=True)

In [289]:
tmp4

array(['year', 'distance', 'name_all_new', 'name_ix', 'name_new_ix',
       'fuel_diesel', 'fuel_gasoline', 'color_black', 'color_gray',
       'color_others', 'color_silver', 'color_white', 'sunroof', 'HID',
       'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack',
       'LED', 'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h',
       'driver_heated_seat', 'driver_ventilated_seat', 'power_steering',
       'steering_remote', 'leahter_seat', 'driver_elec_seat',
       'pass_elec_seat', 'back_elec_seat', 'driver_memory_seat',
       'massage_seat', 'supervision_cluster', 'paddle_shift', 'hi_pass',
       'pass_memory_seat', 'back_heated_seat', 'amb_light', 'walkin_seat',
       'sun_visor', 'pass_ventilated_seat', 'back_ventilated_seat',
       'back_sensor', 'side_airbag', 'driver_airbag', 'pass_airbag',
       'back_camera', 'around_view', 'blackbox', 'ABS', 'ECS', 'TCS',
       'ESC', 'LDWS', 'bur_alarm', 'TPMS', 'knee_airbag',
       'parking_sensor', 'front_carmera', 'AEB', 'smartkey',
       'power_window', 'auto_doorlock', 'fullauto_aircon', 'auto_light',
       'auto_parking', 'elec_parking_break', 'HUD', 'ECM',
       'cruise_control', 'auto_trunk', 'heated_steering',
       'keyless_doorlock', 'rain_sensor', 'stopNgo', 'wireless_charge',
       'navi', 'CDrom', 'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB',
       'handsfree', 'iPod', 'back_monitor', 'mirroring', 'non_genu_navi',
       'bluetooth', 'price'], dtype=object)

In [281]:
tmp = ['fuel_LPG', 'year', 'name_TG']

In [283]:
newDF[tmp] = 1

In [285]:
newDF[tmp]

   fuel_LPG  year  name_TG
0         1     1        1

In [333]:
sample_rand = list(newDF.loc[:, 'sunroof':].columns)
print(sample_rand)

['sunroof', 'HID', 'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack', 'LED', 'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h', 'driver_heated_seat', 'driver_ventilated_seat', 'power_steering', 'steering_remote', 'leahter_seat', 'driver_elec_seat', 'pass_elec_seat', 'back_elec_seat', 'driver_memory_seat', 'massage_seat', 'supervision_cluster', 'paddle_shift', 'hi_pass', 'pass_memory_seat', 'back_heated_seat', 'amb_light', 'walkin_seat', 'sun_visor', 'pass_ventilated_seat', 'back_ventilated_seat', 'back_sensor', 'side_airbag', 'driver_airbag', 'pass_airbag', 'back_camera', 'around_view', 'blackbox', 'ABS', 'ECS', 'TCS', 'ESC', 'LDWS', 'bur_alarm', 'TPMS', 'knee_airbag', 'parking_sensor', 'front_carmera', 'AEB', 'smartkey', 'power_window', 'auto_doorlock', 'fullauto_aircon', 'auto_light', 'auto_parking', 'elec_parking_break', 'HUD', 'ECM', 'cruise_control', 'auto_trunk', 'heated_steering', 'keyless_doorlock', 'rain_sensor', 'stopNgo', 'wireless_charge', 'navi', 'CDrom', 'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB', 'handsfree', 'iPod', 'back_monitor', 'mirroring', 'non_genu_navi', 'bluetooth']

In [348]:
options = ['AUX', 'bluetooth', 'USB']

In [349]:
rand = [random.randint(0, 1) for _ in range(len(sample_rand) - len(options))]
print(rand)

[0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1]

In [372]:
df_options = newDF.loc[:, 'sunroof':]
df_options

,sunroof,HID,Al_wheel,auto_mirror,DLR,sunroof_pano,roof_rack,LED,HBA,ghost_door,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,1,1,0,1,0,1,1,0,1,0,...,0,0,0,1,0,1,1,0,0,0

In [376]:
print([i for i in df_options.columns if i not in options])

['sunroof', 'HID', 'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack', 'LED', 'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h', 'driver_heated_seat', 'driver_ventilated_seat', 'power_steering', 'steering_remote', 'leahter_seat', 'driver_elec_seat', 'pass_elec_seat', 'back_elec_seat', 'driver_memory_seat', 'massage_seat', 'supervision_cluster', 'paddle_shift', 'hi_pass', 'pass_memory_seat', 'back_heated_seat', 'amb_light', 'walkin_seat', 'sun_visor', 'pass_ventilated_seat', 'back_ventilated_seat', 'back_sensor', 'side_airbag', 'driver_airbag', 'pass_airbag', 'back_camera', 'around_view', 'blackbox', 'ABS', 'ECS', 'TCS', 'ESC', 'LDWS', 'bur_alarm', 'TPMS', 'knee_airbag', 'parking_sensor', 'front_carmera', 'AEB', 'smartkey', 'power_window', 'auto_doorlock', 'fullauto_aircon', 'auto_light', 'auto_parking', 'elec_parking_break', 'HUD', 'ECM', 'cruise_control', 'auto_trunk', 'heated_steering', 'keyless_doorlock', 'rain_sensor', 'stopNgo', 'wireless_charge', 'navi', 'CDrom', 'CD_changer', 'av_sys', 'mp3', 'handsfree', 'iPod', 'back_monitor', 'mirroring', 'non_genu_navi']

In [322]:
tmp_df

,sunroof,HID,Al_wheel,auto_mirror,DLR,sunroof_pano,roof_rack,LED,HBA,ghost_door,...,CDrom,CD_changer,av_sys,mp3,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi
0,1,1,1,0,0,1,0,1,0,0,...,1,1,0,0,0,0,1,1,0,0

In [320]:
tmp_df = [random.randint(0, 1) for _ in range]
tmp_df

TypeError: 'type' object is not iterable

In [429]:
options = ['AUX', 'bluetooth', 'USB', 'DLR']
options

['AUX', 'bluetooth', 'USB', 'DLR']

In [430]:
rand = [random.randint(0, 1) for _ in range(len(list(newDF.loc[:, 'sunroof':].columns)) - len(options))]
print(rand)
print(len(rand))

[0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0]
76

In [431]:
newDF.loc[:, [i for i in list(newDF.loc[:, 'sunroof':].columns) if i not in options]]

,sunroof,HID,Al_wheel,auto_mirror,sunroof_pano,roof_rack,LED,HBA,ghost_door,sliding_door,...,navi,CDrom,CD_changer,av_sys,mp3,handsfree,iPod,back_monitor,mirroring,non_genu_navi
0,1,0,1,1,1,1,0,1,1,0,...,0,1,0,1,0,0,1,0,1,0

In [433]:
newDF[options] = 4

In [434]:
newDF.loc[:, [i for i in list(newDF.loc[:, 'sunroof':].columns) if i not in options]] = rand

In [435]:
newDF

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,av_sys,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth
0,1,0,1,0,1,0,0,0,1,1,...,1,1,4,4,0,0,1,1,0,4

In [443]:
newDF.iloc[0, :].value_counts()

0
1    50
0    44
4     4
Name: count, dtype: int64

In [444]:
newDF[options]

   AUX  bluetooth  USB  DLR
0    4          4    4    4

In [449]:
for i in range(5) :
    print('#{}'.format(i+1))

#1
#2
#3
#4
#5

In [451]:
mapper_grandeur = {'그랜저' : 'normal', 
                   '그랜저HG' : 'HG', 
                   '그랜저IG' : 'IG',
                   '그랜저TG' : 'TG', 
                   '더 올 뉴 그랜저' : 'the_all_new', 
                   '더 럭셔리 그랜저' : 'the_luxury', 
                   '더 뉴 그랜저' : 'the_new'}

In [464]:
name = '더 뉴 그랜저'

In [465]:
mapper_grandeur[name]

'the_new'

In [471]:
df = pd.read_csv('./car/tucson_firstName_dummies.csv')

In [472]:
df.columns

Index(['year', 'distance', 'name_all_new', 'name_ix', 'name_new_ix',
       'fuel_diesel', 'fuel_gasoline', 'color_black', 'color_gray',
       'color_others', 'color_silver', 'color_white', 'sunroof', 'HID',
       'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack', 'LED',
       'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h',
       'driver_heated_seat', 'driver_ventilated_seat', 'power_steering',
       'steering_remote', 'leahter_seat', 'driver_elec_seat', 'pass_elec_seat',
       'back_elec_seat', 'driver_memory_seat', 'massage_seat',
       'supervision_cluster', 'paddle_shift', 'hi_pass', 'pass_memory_seat',
       'back_heated_seat', 'amb_light', 'walkin_seat', 'sun_visor',
       'pass_ventilated_seat', 'back_ventilated_seat', 'back_sensor',
       'side_airbag', 'driver_airbag', 'pass_airbag', 'back_camera',
       'around_view', 'blackbox', 'ABS', 'ECS', 'TCS', 'ESC', 'LDWS',
       'bur_alarm', 'TPMS', 'knee_airbag', 'parking_sensor', 'front_carmera',
       'AEB', 'smartkey', 'power_window', 'auto_doorlock', 'fullauto_aircon',
       'auto_light', 'auto_parking', 'elec_parking_break', 'HUD', 'ECM',
       'cruise_control', 'auto_trunk', 'heated_steering', 'keyless_doorlock',
       'rain_sensor', 'stopNgo', 'wireless_charge', 'navi', 'CDrom',
       'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB', 'handsfree', 'iPod',
       'back_monitor', 'mirroring', 'non_genu_navi', 'bluetooth', 'price'],
      dtype='object')

In [475]:
grandeurs = ['그랜저', '그랜저HG', '그랜저IG', '그랜저TG', '더 올 뉴 그랜저', '더 럭셔리 그랜저', '더 뉴 그랜저']
mapper_grandeur = {'그랜저' : 'normal', 
                   '그랜저HG' : 'HG', 
                   '그랜저IG' : 'IG',
                   '그랜저TG' : 'TG', 
                   '더 올 뉴 그랜저' : 'the_all_new', 
                   '더 럭셔리 그랜저' : 'the_luxury', 
                   '더 뉴 그랜저' : 'the_new'}

In [482]:
mapper_grandeur_inv = {v : k for (k, v) in mapper_grandeur.items()}

In [483]:
mapper_grandeur_inv['normal']

'그랜저'

In [484]:
tmp1 = np.load('./model/columns_grandeur.npy', allow_pickle=True)
tmp2 = np.load('./model/columns_k5.npy', allow_pickle=True)
tmp3 = np.load('./model/columns_morning.npy', allow_pickle=True)
tmp4 = np.load('./model/columns_tucson.npy', allow_pickle=True)

In [496]:
color_tmp4 = []
for i in tmp4 :
    if 'color' in i :
        color_tmp4.append(i.split('_')[1])
np.save('./model/colors_tucson', color_tmp4)

In [497]:
tmp1 = np.load('./model/colors_grandeur.npy', allow_pickle=True)

In [498]:
tmp1

array(['black', 'gray', 'others', 'silver', 'white'], dtype='<U6')

In [500]:
dict(tmp1)

ValueError: dictionary update sequence element #0 has length 5; 2 is required

In [502]:
df = pd.read_csv('./car/grandeur_firstName_dummies.csv')
df

,year,distance,name_HG,name_IG,name_TG,name_normal,name_the_all_new,name_the_luxury,name_the_new,fuel_LPG,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,14,121523,True,False,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,790
1,19,69368,False,True,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,2190
2,18,94692,False,True,False,False,False,False,False,False,...,0,1,1,0,1,0,0,0,1,1990
3,18,79252,False,True,False,False,False,False,False,True,...,0,1,0,0,0,0,0,0,0,1795
4,18,139269,False,True,False,False,False,False,False,False,...,0,1,1,0,0,0,1,0,1,1339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,10,97366,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,590
1973,11,170000,True,False,False,False,False,False,False,False,...,1,1,1,1,0,0,0,0,0,459
1974,19,120000,False,True,False,False,False,False,False,False,...,0,1,0,0,0,0,0,0,0,1690
1975,13,128220,True,False,False,False,False,False,False,True,...,0,1,1,0,0,0,0,0,0,979
1976,21,82312,False,False,False,False,False,False,True,False,...,0,0,0,0,0,0,0,0,0,3350