In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [160]:
df = pd.read_csv('./car/tucson_engColumns.csv')
df

,name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,DLR,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,현대 올 뉴 투싼 디젤(e-VGT R,17,diesel,134579,gray,0,0,1,1,1,...,1,1,1,0,0,0,0,0,0,1260
1,현대 올 뉴 투싼 디젤(e-VGT R,18,diesel,101682,white,1,1,1,1,1,...,0,0,1,1,0,0,0,0,1,1850
2,현대 올 뉴 투싼 디젤(e-VGT R,17,diesel,168000,gray,0,0,1,1,1,...,0,1,0,0,0,0,0,0,0,1299
3,현대 투싼ix 디젤 2WD LX20 럭셔리,9,diesel,64239,gray,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,700
4,현대 뉴 투싼 ix 디젤(e-VGT,13,diesel,149044,gray,0,0,1,1,0,...,0,1,1,0,0,0,0,0,1,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,현대 올 뉴 투싼 가솔린 (Turbo GDi,20,gasoline,49348,white,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,2250
1928,현대 투싼ix 디젤 2WD LX20 모던,13,diesel,180871,white,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,700
1929,현대 뉴 투싼 ix 디젤(e-VGT,13,diesel,162130,white,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,770
1930,현대 올 뉴 투싼 디젤(e-VGT R,18,diesel,61187,gray,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1899
1931,현대 올 뉴 투싼 디젤(e-VGT UⅡ,15,diesel,114415,others,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1190

In [161]:
df['name'][1][3:]

'올 뉴 투싼 디젤(e-VGT R'

In [162]:
df['name'] = df['name'].apply(lambda x : x[3:])
df

,name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,DLR,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,올 뉴 투싼 디젤(e-VGT R,17,diesel,134579,gray,0,0,1,1,1,...,1,1,1,0,0,0,0,0,0,1260
1,올 뉴 투싼 디젤(e-VGT R,18,diesel,101682,white,1,1,1,1,1,...,0,0,1,1,0,0,0,0,1,1850
2,올 뉴 투싼 디젤(e-VGT R,17,diesel,168000,gray,0,0,1,1,1,...,0,1,0,0,0,0,0,0,0,1299
3,투싼ix 디젤 2WD LX20 럭셔리,9,diesel,64239,gray,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,700
4,뉴 투싼 ix 디젤(e-VGT,13,diesel,149044,gray,0,0,1,1,0,...,0,1,1,0,0,0,0,0,1,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,올 뉴 투싼 가솔린 (Turbo GDi,20,gasoline,49348,white,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,2250
1928,투싼ix 디젤 2WD LX20 모던,13,diesel,180871,white,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,700
1929,뉴 투싼 ix 디젤(e-VGT,13,diesel,162130,white,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,770
1930,올 뉴 투싼 디젤(e-VGT R,18,diesel,61187,gray,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1899
1931,올 뉴 투싼 디젤(e-VGT UⅡ,15,diesel,114415,others,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1190

In [163]:
' '.join(df['name'][1900].split(' ')[:3])

'올 뉴 투싼'

In [164]:
df['name'].unique()

array(['올 뉴 투싼 디젤(e-VGT R', '투싼ix 디젤 2WD LX20 럭셔리', '뉴 투싼 ix 디젤(e-VGT',
       '투싼ix 디젤 2WD X20 스마트', '올 뉴 투싼 디젤(e-VGT UⅡ', '투싼ix 디젤 2WD X20 럭셔리',
       '투싼ix 디젤 4WD X20 럭셔리', '올 뉴 투싼 가솔린 (Turbo GDi',
       '투싼ix 디젤 2WD LMX20 프리미엄', '투싼ix 디젤 2WD LX20 프리미어',
       '올 뉴 투싼 가솔린(Turbo GDi', '투싼ix 디젤 2WD LX20 스마트팩',
       '투싼ix 디젤 4WD LX20 프리미어', '투싼ix 가솔린 2WD X20 워너비',
       '투싼ix 디젤 2WD X20 스페셜 팩', '투싼ix 디젤 2WD X20 디럭스',
       '투싼ix 가솔린 2WD LX20 프리미어', '투싼ix 디젤 4WD LMX20 프리미엄',
       '투싼ix 디젤 2WD LX20 모던', '투싼ix 디젤 4WD X20 스마트',
       '투싼ix 가솔린 2WD LMX20 프리미어', '투싼ix 디젤 4WD X20 스타일',
       '뉴 투싼 ix 가솔린 2.0 GDI 2WD 스페셜', '뉴 투싼 ix 가솔린 2.0 GDI 2WD 스타일',
       '뉴 투싼 ix 가솔린 2.0 GDI 2WD 모던', '투싼ix 디젤 4WD LX20 모던',
       '투싼ix 가솔린 2WD LX20 럭셔리'], dtype=object)

In [165]:
def first_name(name) :
    for i in range(len(name.split(' '))) :
        if 'ix' in name.split(' ')[i] :
            tmp = ' '.join(name.split(' ')[:i+1])
        elif '투싼' in name.split(' ')[i] :
            tmp = ' '.join(name.split(' ')[:i+1])
    return tmp

In [166]:
df['first_name'] = df['name'].apply(lambda x : first_name(x))
df

,name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,DLR,...,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price,first_name
0,올 뉴 투싼 디젤(e-VGT R,17,diesel,134579,gray,0,0,1,1,1,...,1,1,0,0,0,0,0,0,1260,올 뉴 투싼
1,올 뉴 투싼 디젤(e-VGT R,18,diesel,101682,white,1,1,1,1,1,...,0,1,1,0,0,0,0,1,1850,올 뉴 투싼
2,올 뉴 투싼 디젤(e-VGT R,17,diesel,168000,gray,0,0,1,1,1,...,1,0,0,0,0,0,0,0,1299,올 뉴 투싼
3,투싼ix 디젤 2WD LX20 럭셔리,9,diesel,64239,gray,0,0,1,0,0,...,1,0,0,0,0,0,0,0,700,투싼ix
4,뉴 투싼 ix 디젤(e-VGT,13,diesel,149044,gray,0,0,1,1,0,...,1,1,0,0,0,0,0,1,720,뉴 투싼 ix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,올 뉴 투싼 가솔린 (Turbo GDi,20,gasoline,49348,white,0,0,1,1,0,...,0,0,0,0,0,0,0,0,2250,올 뉴 투싼
1928,투싼ix 디젤 2WD LX20 모던,13,diesel,180871,white,1,0,0,0,0,...,0,0,0,0,0,0,0,0,700,투싼ix
1929,뉴 투싼 ix 디젤(e-VGT,13,diesel,162130,white,0,0,0,0,0,...,0,0,0,0,0,0,0,0,770,뉴 투싼 ix
1930,올 뉴 투싼 디젤(e-VGT R,18,diesel,61187,gray,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1899,올 뉴 투싼
1931,올 뉴 투싼 디젤(e-VGT UⅡ,15,diesel,114415,others,1,0,1,1,0,...,0,0,0,0,0,0,0,0,1190,올 뉴 투싼

In [167]:
df.columns

Index(['name', 'year', 'fuel', 'distance', 'color', 'sunroof', 'HID',
       'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack', 'LED',
       'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h',
       'driver_heated_seat', 'driver_ventilated_seat', 'power_steering',
       'steering_remote', 'leahter_seat', 'driver_elec_seat', 'pass_elec_seat',
       'back_elec_seat', 'driver_memory_seat', 'massage_seat',
       'supervision_cluster', 'paddle_shift', 'hi_pass', 'pass_memory_seat',
       'back_heated_seat', 'amb_light', 'walkin_seat', 'sun_visor',
       'pass_ventilated_seat', 'back_ventilated_seat', 'back_sensor',
       'side_airbag', 'driver_airbag', 'pass_airbag', 'back_camera',
       'around_view', 'blackbox', 'ABS', 'ECS', 'TCS', 'ESC', 'LDWS',
       'bur_alarm', 'TPMS', 'knee_airbag', 'parking_sensor', 'front_carmera',
       'AEB', 'smartkey', 'power_window', 'auto_doorlock', 'fullauto_aircon',
       'auto_light', 'auto_parking', 'elec_parking_break', 'HUD', 'ECM',
       'cruise_control', 'auto_trunk', 'heated_steering', 'keyless_doorlock',
       'rain_sensor', 'stopNgo', 'wireless_charge', 'navi', 'CDrom',
       'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB', 'handsfree', 'iPod',
       'back_monitor', 'mirroring', 'non_genu_navi', 'bluetooth', 'price',
       'first_name'],
      dtype='object')

In [168]:
df = df[['name', 'first_name', 'year', 'fuel', 'distance', 'color', 'sunroof', 'HID',
       'Al_wheel', 'auto_mirror', 'DLR', 'sunroof_pano', 'roof_rack', 'LED',
       'HBA', 'ghost_door', 'sliding_door', 'side_step', 'adap_h',
       'driver_heated_seat', 'driver_ventilated_seat', 'power_steering',
       'steering_remote', 'leahter_seat', 'driver_elec_seat', 'pass_elec_seat',
       'back_elec_seat', 'driver_memory_seat', 'massage_seat',
       'supervision_cluster', 'paddle_shift', 'hi_pass', 'pass_memory_seat',
       'back_heated_seat', 'amb_light', 'walkin_seat', 'sun_visor',
       'pass_ventilated_seat', 'back_ventilated_seat', 'back_sensor',
       'side_airbag', 'driver_airbag', 'pass_airbag', 'back_camera',
       'around_view', 'blackbox', 'ABS', 'ECS', 'TCS', 'ESC', 'LDWS',
       'bur_alarm', 'TPMS', 'knee_airbag', 'parking_sensor', 'front_carmera',
       'AEB', 'smartkey', 'power_window', 'auto_doorlock', 'fullauto_aircon',
       'auto_light', 'auto_parking', 'elec_parking_break', 'HUD', 'ECM',
       'cruise_control', 'auto_trunk', 'heated_steering', 'keyless_doorlock',
       'rain_sensor', 'stopNgo', 'wireless_charge', 'navi', 'CDrom',
       'CD_changer', 'av_sys', 'mp3', 'AUX', 'USB', 'handsfree', 'iPod',
       'back_monitor', 'mirroring', 'non_genu_navi', 'bluetooth', 'price'
       ]]

In [169]:
df

,name,first_name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,올 뉴 투싼 디젤(e-VGT R,올 뉴 투싼,17,diesel,134579,gray,0,0,1,1,...,1,1,1,0,0,0,0,0,0,1260
1,올 뉴 투싼 디젤(e-VGT R,올 뉴 투싼,18,diesel,101682,white,1,1,1,1,...,0,0,1,1,0,0,0,0,1,1850
2,올 뉴 투싼 디젤(e-VGT R,올 뉴 투싼,17,diesel,168000,gray,0,0,1,1,...,0,1,0,0,0,0,0,0,0,1299
3,투싼ix 디젤 2WD LX20 럭셔리,투싼ix,9,diesel,64239,gray,0,0,1,0,...,0,1,0,0,0,0,0,0,0,700
4,뉴 투싼 ix 디젤(e-VGT,뉴 투싼 ix,13,diesel,149044,gray,0,0,1,1,...,0,1,1,0,0,0,0,0,1,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,올 뉴 투싼 가솔린 (Turbo GDi,올 뉴 투싼,20,gasoline,49348,white,0,0,1,1,...,0,0,0,0,0,0,0,0,0,2250
1928,투싼ix 디젤 2WD LX20 모던,투싼ix,13,diesel,180871,white,1,0,0,0,...,0,0,0,0,0,0,0,0,0,700
1929,뉴 투싼 ix 디젤(e-VGT,뉴 투싼 ix,13,diesel,162130,white,0,0,0,0,...,0,0,0,0,0,0,0,0,0,770
1930,올 뉴 투싼 디젤(e-VGT R,올 뉴 투싼,18,diesel,61187,gray,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1899
1931,올 뉴 투싼 디젤(e-VGT UⅡ,올 뉴 투싼,15,diesel,114415,others,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1190

In [170]:
df['first_name'].value_counts()

first_name
올 뉴 투싼     1154
투싼ix        472
뉴 투싼 ix     306
Name: count, dtype: int64

In [171]:
set(df['first_name'])

{'뉴 투싼 ix', '올 뉴 투싼', '투싼ix'}

In [153]:
set(df[df['first_name'] == '뉴모닝 SLX']['fuel'])

{'gasoline'}

In [172]:
mapper = {'뉴 투싼 ix' : 'new_ix', 
          '올 뉴 투싼' : 'all_new', 
          '투싼ix' : 'ix'}

In [173]:
df['first_name'] = df['first_name'].map(mapper)
df

,name,first_name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,올 뉴 투싼 디젤(e-VGT R,all_new,17,diesel,134579,gray,0,0,1,1,...,1,1,1,0,0,0,0,0,0,1260
1,올 뉴 투싼 디젤(e-VGT R,all_new,18,diesel,101682,white,1,1,1,1,...,0,0,1,1,0,0,0,0,1,1850
2,올 뉴 투싼 디젤(e-VGT R,all_new,17,diesel,168000,gray,0,0,1,1,...,0,1,0,0,0,0,0,0,0,1299
3,투싼ix 디젤 2WD LX20 럭셔리,ix,9,diesel,64239,gray,0,0,1,0,...,0,1,0,0,0,0,0,0,0,700
4,뉴 투싼 ix 디젤(e-VGT,new_ix,13,diesel,149044,gray,0,0,1,1,...,0,1,1,0,0,0,0,0,1,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,올 뉴 투싼 가솔린 (Turbo GDi,all_new,20,gasoline,49348,white,0,0,1,1,...,0,0,0,0,0,0,0,0,0,2250
1928,투싼ix 디젤 2WD LX20 모던,ix,13,diesel,180871,white,1,0,0,0,...,0,0,0,0,0,0,0,0,0,700
1929,뉴 투싼 ix 디젤(e-VGT,new_ix,13,diesel,162130,white,0,0,0,0,...,0,0,0,0,0,0,0,0,0,770
1930,올 뉴 투싼 디젤(e-VGT R,all_new,18,diesel,61187,gray,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1899
1931,올 뉴 투싼 디젤(e-VGT UⅡ,all_new,15,diesel,114415,others,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1190

In [174]:
df = df[df['price'] < 8000].reset_index(drop=True)

In [177]:
df

,name,first_name,year,fuel,distance,color,sunroof,HID,Al_wheel,auto_mirror,...,mp3,AUX,USB,handsfree,iPod,back_monitor,mirroring,non_genu_navi,bluetooth,price
0,올 뉴 투싼 디젤(e-VGT R,all_new,17,diesel,134579,gray,0,0,1,1,...,1,1,1,0,0,0,0,0,0,1260
1,올 뉴 투싼 디젤(e-VGT R,all_new,18,diesel,101682,white,1,1,1,1,...,0,0,1,1,0,0,0,0,1,1850
2,올 뉴 투싼 디젤(e-VGT R,all_new,17,diesel,168000,gray,0,0,1,1,...,0,1,0,0,0,0,0,0,0,1299
3,투싼ix 디젤 2WD LX20 럭셔리,ix,9,diesel,64239,gray,0,0,1,0,...,0,1,0,0,0,0,0,0,0,700
4,뉴 투싼 ix 디젤(e-VGT,new_ix,13,diesel,149044,gray,0,0,1,1,...,0,1,1,0,0,0,0,0,1,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,올 뉴 투싼 가솔린 (Turbo GDi,all_new,20,gasoline,49348,white,0,0,1,1,...,0,0,0,0,0,0,0,0,0,2250
1928,투싼ix 디젤 2WD LX20 모던,ix,13,diesel,180871,white,1,0,0,0,...,0,0,0,0,0,0,0,0,0,700
1929,뉴 투싼 ix 디젤(e-VGT,new_ix,13,diesel,162130,white,0,0,0,0,...,0,0,0,0,0,0,0,0,0,770
1930,올 뉴 투싼 디젤(e-VGT R,all_new,18,diesel,61187,gray,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1899
1931,올 뉴 투싼 디젤(e-VGT UⅡ,all_new,15,diesel,114415,others,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1190

In [178]:
df['first_name'].value_counts()

first_name
all_new    1154
ix          472
new_ix      306
Name: count, dtype: int64

In [179]:
df.to_csv('./car/tucson_firstName.csv', index=False)